name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

    - name: Format code
      run: |
        pip install black
        pip install black[jupyter]
        black --check .
      continue-on-error: true

    - name: Format code and push changes
      if: steps.black.outcome == 'failure'
      run: |
        black .
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Format code using black'
        git push origin main
      continue-on-error: true

    - name: Lint code
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true

    - name: Test code
      run: |
        pip install pytest
        pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Github Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/smart-recipe:latest
          ghcr.io/${{ github.repository_owner }}/smart-recipe:${{ github.sha }}
    
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}